### ISSUE TITLE
Support grid_size option for polygon input

### ISSUE THREAD

**Issue by jdubowy** [pnwairfire/bluesky-web#55]
when grid_size < 1, the code determines a new grid, within the met domain, centered as much as possible around the fire lat,lng.  For polygon, we just need to reduce the polygon to it's centroid and  plug that into the calculation.

## TODO

 - [x] write method to compute centroid of polygon, multi polygons, multi points, etc., and then centroid of centroids if multiple growth objects
 - [x] add and update unit tests
 - [x] ad hoc tests (web regression and test async
 - [x] deploy
